#!/usr/bin/env bash

add () {
    # Given a field separator and n, add the nth field for all lines in stdout
    awk -v FS=$1 -v N=$2 '{ SUM += $N } END { print SUM }'
}

average () {
    # Given a field separator and n, average the nth field for all lines in stdout
    awk -v FS=$1 -v N=$2 '{ SUM += $N; COUNT += 1 } END { print SUM/COUNT }'
}
